package jorgecasariego.databasewithroom.entities;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

/**
 * - Entity: defines the table name of the database
 * - PrimaryKey: defines the (autogenerated) unique id to be handled as primary key by database
 * - ColumnInfo: defines the column name of the current table
 *
 * Created by jorgecasariego on 14/9/17.
 */
@Entity
public class Usuario {
    @PrimaryKey(autoGenerate = true)
    private int uid;

    @ColumnInfo(name = "nombre")
    private String nombre;

    @ColumnInfo(name = "password")
    private String password;

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return nombre + " " + password;
    }
}
